### ISSUE TITLE
UI component for page related actions

### ISSUE THREAD

**Issue by CraigCav** [ezcater/recipe#357]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Some good questions to answer are:

- When should this component be used?
- When shouldn’t it be used? For those cases, is there an alternative component you’d recommend (and why do you recommend it)?
- When should each variation of the component be used?
- What are guidelines for the content that could go into this component?
- Are there limitations/restrictions on what it can handle?
- Is anything not going into this first version? What did you exclude and what was the reasoning behind that?

**Design Mockups**

![image](https://user-images.githubusercontent.com/109814/81707578-bf80e480-943e-11ea-8e86-9d24425e1121.png)

Add any other context and screenshots about the feature request here.

**Comment by CraigCav** [comment]
Maybe we could do something similar to https://react-spectrum.adobe.com/react-spectrum/ActionGroup.html

**Comment by noranda** [comment]
[`EzStatus`](https://ezcater.github.io/recipe/components/ez-status) was recently deprecated in favor of [`EzChip`](https://ezcater.github.io/recipe/components/ez-chip#status) with status variants. `EzChip` also supports all theme colors. [`EzWell`](https://ezcater.github.io/recipe/components/ez-well) was also added since this issue and will soon be refactored to support theme colors as well. Closing issue as not planned.
