### ISSUE TITLE
Multiselect

### ISSUE THREAD

**Issue by tylerhathawayEZ** [ezcater/recipe#416]
**Is your feature request related to a problem? Please describe.**

Currently no component for multiselect

**Describe the solution you'd like**

- selecting multiple filters for a search, selecting multiple entities (ex: drivers, stores), selecting multiple tags, etc
- 2 versions attached, V1 is probably more intuitive but V2 saves a click on most of the actions

**Design Mockups**

![multiselect-MVP](https://user-images.githubusercontent.com/67985121/91345010-bb3dc480-e7ac-11ea-9af1-eee3c2256353.png)

**Comment by ez-alexfrazer** [comment]
I got some questions if you don't mind me adding to the conversation:

- Should pagination be supported?
- If so, does that mean we should likely add virtualization or windowing? (i.e., infinite scroll)
- If that is true, how will a user be able to see their previous selected items? Maybe they're omni-present in the search/selection/paging?
- What does a blank state look like? i.e., when you have no options and no search results?

**Comment by CraigCav** [comment]
@ez-alexfrazer I'd definitely be interested in hearing a little bit more about the use case that requires this feature.

For example: "In [whatever app] we want users to be able to select up to [x number] of options from a list of [resource] in order to [action]. It's not uncommon for [resource] to have between [y] and [z] number of records to choose from".

From a visual design perspective, I'd be curious what other options folks have considered. 

For example, "we've also considered multi-select list boxes (as pictured below), but ruled this option out because [reason]":

![image](https://user-images.githubusercontent.com/109814/126508061-45156905-bf56-4e03-8e2d-da114a0fac7e.png)

**Comment by noranda** [comment]
In a future refactor for `EzSelect`, we will use MUI's [implementation](https://mui.com/material-ui/react-select/#checkmarks) to support multiple selections. Closing this issue. Added to [Recipe Ideas](https://github.com/ezcater/recipe/discussions/871) discussion.
