### ISSUE TITLE
Support sorting columns with custom cell rendering

### ISSUE THREAD

**Issue by jbelang** [ezcater/recipe#645]
I have been looking into replacing ezManage's use of Semantic table with EzTable, but one thing stands in the way: "Sorting columns with custom cell rendering is currently not supported." We have all the different pieces needed for these tables - sorting, custom cells, pagination, actions in the header - but they don't all work together.

Ideally, EzTable would support sorting columns with custom cells so that we could convert:
- Customers table
- EzD preferences table
- PaymentDetails table
- Payments table
- Performance table

This will help us toward our goal of removing Semantic from ezManage and switching entirely to Recipe.

**Comment by CraigCav** [comment]
@jbelang So the good news is, this is already possible today. [Example](https://ezcater.github.io/recipe/playroom/?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgJZG1W0CGANgJJUwC2F2GAbWKlSwIs24x4GAOQApCMxJyYVKjIA0GahABOMAMIQArkSrSAjACYAvhuEixEqbIAizAG60oGAEIQAd1oYTW0qPUMTM2kANjsHUXFJaRkAZQALGBhxDABRZh0iUJ19I1NzDDj7EkcklzSuLxgMADlaMABrCmLw0qiKi3iagF0AbgcHcmpW5yNWY24SLAxkYEYeLVZ6DoAlGAAzG0xcFYSMAB4oWg8cM9JL69uakRFz5gx0-X2sAhAAYl%2BGC%2BWGAWyIuwONgwECIBi2nRB6GweDYMF0VGQJRgaBsTxe%2BPw624ADo6jY7q8APTMPH486Uq43M70xm0tDjIiTGHTAAqzAARqxmsskSdCM8yNyaAIiRQtMYAA5QZhcTg8CjDfh7ZhgKjE4wUGCpKgqmDIeiMFgcLi8dnEM5TGgw1J6Khw9odfjIAD6MA82SoWmAkHmiy0V30utoMKOyPwFMdGCIMACat4-AExKzFqYbDTGuJFFdqGYWn5xzw4oJpETHjYFn4zAEIYWRGJHRgAE8xhSa1KMHXWFZ%2BPzmxBQ22O92Ob2gapjLoSMgIzAozDsFhljICmAZBgAPwD%2BsYPCD4fSQcN85HoeYQ8N6QAWgsHIJRxnEtIiuVqptFGQyapn%2BdoSjYH4vPoVALkuFLnLkABeAAKzAAOYwLSBJwfBfKCjAs6kEwVBCj8IDGhEGAAPIBMmugUL8%2BHQkQLrou6CLAM6rqsR05KfviLaLBQIJCLxBLAJkzBXEQKEpC0zihFOKR1MUroCkK0hULoxgwFokDcAqMIBtIsmSHMrZDNW%2BJiTAEn0NJshkfoGBlGY8ldikWLOeoWhFuiqkuBpWnhgczDGKwVDMRUMiwBQu7mRZGDDDx8V0H%2BIKykl1aUhhVIIchaHZSBpBgfaNSQdBFw4UKGBZRyRzoDYIA2EAA).

I believe this has been possible for some time, since @stacy-wells added all the necessary ingredients as part of #316.

So I **_think_** the remaining work is here to get our ducks in a row with our docs to ensure folks know about this feature and how to use it (and to remove the line telling people it's not possible!).
